### ISSUE TITLE
Use library with elements

### ISSUE THREAD

**Issue by afeezaziz** [vulpemventures/liquidjs-lib#112]
hello @tiero @altafan 

[exports.liquid = {
  messagePrefix: '\x18Liquid Signed Message:\n',
  bech32: 'ex',
  blech32: 'lq',
  bip32: {
    public: 0x0488b21e,
    private: 0x0488ade4,
  },
  pubKeyHash: 57,
  scriptHash: 39,
  wif: 0x80,
  confidentialPrefix: 12,
  assetHash: '6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d',
  genesisBlockHash: LiquidGenesisBlockHash,
  name: 'liquid',
};](https://github.com/vulpemventures/liquidjs-lib/blob/ad52d69db77d8a0c609c3b52ef43dbb7be12a007/src/networks.js#L14C1-L14C1)

How do I get the values for most of the keys here if I am running an Element standalone chain?

**Comment by altafan** [comment]
You may find `getnetworkinfo` and `getblockchaininfo` commands useful

**Comment by afeezaziz** [comment]
Hello,

How do i set based on `getnetworkinfo` and `getblockchaininfo` and set it to work with this library?

**Comment by altafan** [comment]
Not sure I got your question.

If you are running your blockchain with elements and you customized these variables, like the prefix of the address types or whatever, you'll have to fork this lib and update the params listed [here](https://github.com/vulpemventures/liquidjs-lib/issues/112#issue-2072213801) accordingly.

**Comment by tiero** [comment]
For is not necessary I guess? You can source your own Network object

**Comment by afeezaziz** [comment]
> Not sure I got your question.
> 
> If you are running your blockchain with elements and you customized these variables, like the prefix of the address types or whatever, you'll have to fork this lib and update the params listed [here](https://github.com/vulpemventures/liquidjs-lib/issues/112#issue-2072213801) accordingly.

What I am trying to say is that, I am not running a custom blockchain, but just a standard Elements blockchain. I just follow the tutorial. Exactly like the [tutorial](https://elementsproject.org/elements-code-tutorial/blockchain).

There is examples based on python, c#, and so on to interact with the blockchain but there is no sample to communicate with the blockchain such as generating receiving address and so on using javascript.

**Comment by afeezaziz** [comment]
> For is not necessary I guess? You can source your own Network object

I do not understand your statement.

**Comment by tiero** [comment]
Liquid is the only live blockchain I am aware of, that runs as a sidechain of Bitcoin. This library works with Liquid and any elements chain, but every chain has its own Network parameters. If you run your standalone blockchain, these parameters will be different, so you need to supply them to LiquidJS.

@afeezaziz Are you in touch with Blockstream? I think nobody ever deployed to production a standalone Elements blockchain and would be best to have them to support you. If you are just experimenting, start using Liquid first, there is a public test net as well!

**Comment by afeezaziz** [comment]
> Liquid is the only live blockchain I am aware of, that runs as a sidechain of Bitcoin. This library works with Liquid and any elements chain, but every chain has its own Network parameters. If you run your standalone blockchain, these parameters will be different, so you need to supply them to LiquidJS.
> 
> @afeezaziz Are you in touch with Blockstream? I think nobody ever deployed to production a standalone Elements blockchain and would be best to have them to support you. If you are just experimenting, start using Liquid first, there is a public test net as well!

Hello, I am testing on elements chain, running on my laptop, not production level. I do not intend to run a non-sidechain blockchain... In fact not interested to run a blockchain hahaha.

I would like to use the library to interact with elements and liquid. I am more concerned about using elements chain.

**Comment by tiero** [comment]
> . I am more concerned about using elements chain.

Yes, this is what we are trying to explain :) you can use it, but need to use the right prefix if you use your custom elements chain.

Please get confident with Liquid (I suggest to use https://github.com/vulpemventures/nigiri), then you move to Elements
