### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by afeezaziz** [vulpemventures/liquidjs-lib#113]
Can you please provide examples on how:

1. generate addresses using bech32 or alternative address

2. mint asset on liquid/elements

3. transfer other assets other than L-BTC on liquid/elements

**Comment by tiero** [comment]
In general look into `tests/integration`, that should include a lot of examples.

1. If you come from BitcoinJS you should find very similar API, at least for what concern `payments` instance. https://github.com/vulpemventures/liquidjs-lib/blob/master/test/integration/addresses.spec.ts

2. Attach issuance data ina Liquid tx https://github.com/vulpemventures/liquidjs-lib/blob/master/test/integration/psetv2.spec.ts#L837

3. Create a normal bitcoin-like tx and specify asset hash for each different output of the new utxo your creating https://github.com/vulpemventures/liquidjs-lib/blob/master/test/integration/psetv2.spec.ts#L37

**Comment by afeezaziz** [comment]
Thank you @tiero additional questions, how do I

1. get liquid balance?

2. get other assets balance?

**Comment by altafan** [comment]
You can fetch such info from an explorer like Blockstream's esplora: https://blockstream.info/liquid.

Check the doc for all the available endpoints https://github.com/Blockstream/esplora/blob/master/API.md.

**Comment by afeezaziz** [comment]
> You can fetch such info from an explorer like Blockstream's esplora: https://blockstream.info/liquid.
> 
> Check the doc for all the available endpoints https://github.com/Blockstream/esplora/blob/master/API.md.

Hello, for the assets on Liquid and Elements, I did check out the documentation of esplora, but I could not find balance of assets that can be retrieved via esplora.

I would like to get balance of default asset of an Element chain or Liquid and balance of whatever assets that the wallet hold.

**Comment by tiero** [comment]
Do you have experience with Bitcoin and UTXO model in general? otherwise is very hard to give code snippets/examples, as you will enter in many more problems down the road if you understand how the blockchain works

**Comment by afeezaziz** [comment]
I would like to see how and if get balance of the liquid/elements assets by using this library. If there is no test or example in this library, then it is ok.

**Comment by tiero** [comment]
Again, if you don't know how UTXO-model works would be hard (and you will not ask this question) 

Because LiquidJS is similar to BitcoinJS, you need to create your own logic to fetch UTXOs via an explorer or a node, unblind etc..

**Comment by afeezaziz** [comment]
Ok, thank you. Now I know that this library cannot get balances of liquid assets. I have to use own liquid or elements node.

A big or small(?) difference between Bitcoin and Elements is that Bitcoin does not have asset issuance so small difference between the libraries, whether this library can support the extra features from liquid.

A faster way to answer this question would be: No, this library cannot be used to get liquid asset balances. 

Thank you guys!

**Comment by bordalix** [comment]
@afeezaziz this link is for an archived repo, but good enough for you to see how some high level operations (like balances) where made, and who knows, to copy & paste some code 😉 

https://github.com/vulpemventures/ldk/blob/master/src/balance.ts
