### ISSUE TITLE
Issuance from confidential input

### ISSUE THREAD

**Issue by asoltys** [vulpemventures/liquidjs-lib#16]
Hi I'm trying to create an asset issuance transaction where the input is coming from a utxo that has been unblinded, but I'm getting an error when I attempt to broadcast it:

`sendrawtransaction RPC error: {"code":-26,"message":"bad-txns-in-ne-out, value in != value out (code 16)"}`

I've created a reproduction here: https://github.com/asoltys/repro

I'm not sure if I'm doing something wrong with the blinding/unblinding or if there's something else causing the tx to be invalid. Can anyone else shed some light?

I tried stepping through the elements source code with gdb to see what was causing that error message to throw and I think it was to do with the surjection proof failing to verify but I'm not exactly confident about that analysis either :)

```
    if (secp256k1_surjectionproof_verify(secp256k1_ctx_verify_amounts, &proof, vTags.data(), vTags.size(), &gen) != 1) {
        return false;
    }
```

Signed tx JSON:

```
{
  "txid": "9620919c4111dfe7fcfba8494135f55f111b3918de5d132155029071c0dbcdb0",
  "hash": "b1592252271d75d409b2b0319ef33e1ec2413b533191302a8c57fe997f199f93",
  "wtxid": "b1592252271d75d409b2b0319ef33e1ec2413b533191302a8c57fe997f199f93",
  "withash": "6ac5ba6c61bb8b117ba8bc7003ca89804ef9c588c45050efd594e53101abe97f",
  "version": 2,
  "size": 3511,
  "vsize": 1201,
  "weight": 4804,
  "locktime": 0,
  "vin": [
    {
      "txid": "a5c80150cd866ff3d5f9c2832fbe19bef0dffe049146ec38b222634e41cb14b0",
      "vout": 0,
      "scriptSig": {
        "asm": "0014a73a66c6a7a1d911cc42db68da4e69d743def311",
        "hex": "160014a73a66c6a7a1d911cc42db68da4e69d743def311"
      },
      "is_pegin": false,
      "sequence": 4294967295,
      "txinwitness": [
        "30440220225d5a24f1e714cfd01966bb4ba840ce685f9f6f12a1b8b22e26998acc039c1102206bc06ff6128098ec72165f3e3800ef77f033b4c641da6c7ef8987e6a2ffd108a01",
        "02c3bacbfa8b54fde3e318a9c10e07a65b0a9b1c7bc01ad210297b217d3859e383"
      ],
      "issuance": {
        "assetBlindingNonce": "0000000000000000000000000000000000000000000000000000000000000000",
        "assetEntropy": "1323f19866da5a1beb40e33daf864d5e1f645ffdba28ef574ef387625a7ba9f3",
        "isreissuance": false,
        "token": "a210c3bc70e01de591c18de53528daa9b40fba078bf729b7245eb28be428e07f",
        "asset": "4336ccde4e1270bc563ed4fe3049b6cfbfdcda2a0fc9841569637aa8129adabb",
        "assetamount": 0.00000001
      }
    }
  ],
  "vout": [
    {
      "value": 0.00000000,
      "asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
      "commitmentnonce": "",
      "commitmentnonce_fully_valid": false,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_RETURN 12336",
        "hex": "6a023030",
        "type": "nulldata"
      }
    },
    {
      "value-minimum": 0.00000001,
      "value-maximum": 687.19476736,
      "ct-exponent": 0,
      "ct-bits": 36,
      "surjectionproof": "010001a50506aa38b4f41be620c5b2c824bed6028dc2ba02bc10bed7f826efbca0b0eedfd5ebfdc91b0cd89ef1ff7a6ad71780eaa450754898299e9ecb366a1cba4ca2",
      "valuecommitment": "0863b420c431f631036465be5f9c8820a9d59d49083af68ead46773a48a13e684b",
      "assetcommitment": "0b0a6e60edff3fb239b36ad76b6164474e4c2100ce0bafd3cf1f61404268a4fc9c",
      "commitmentnonce": "025115a71781dce1639262595910c184d2a02985daa827f2a69fe3fbf9a49f9a2b",
      "commitmentnonce_fully_valid": true,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 0b37147242422e9024c5d9e20414b029b3b0cea8 OP_EQUAL",
        "hex": "a9140b37147242422e9024c5d9e20414b029b3b0cea887",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "XCNYGGh7KvKAFkGVcrSpw3CCAmmnPDzv2n"
        ]
      }
    },
    {
      "value": 0.00000001,
      "asset": "4336ccde4e1270bc563ed4fe3049b6cfbfdcda2a0fc9841569637aa8129adabb",
      "commitmentnonce": "",
      "commitmentnonce_fully_valid": false,
      "n": 2,
      "scriptPubKey": {
        "asm": "OP_HASH160 0b37147242422e9024c5d9e20414b029b3b0cea8 OP_EQUAL",
        "hex": "a9140b37147242422e9024c5d9e20414b029b3b0cea887",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "XCNYGGh7KvKAFkGVcrSpw3CCAmmnPDzv2n"
        ]
      }
    },
    {
      "value": 0.00000300,
      "asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
      "commitmentnonce": "",
      "commitmentnonce_fully_valid": false,
      "n": 3,
      "scriptPubKey": {
        "asm": "",
        "hex": "",
        "type": "fee"
      }
    }
  ]
}

```

**Comment by tiero** [comment]
At the moment, we tested the #4 issuance flow with unconfidential onl. So not sure if we need extra step here


cc @louisinger

**Comment by louisinger** [comment]
Hello @asoltys, looking at your `repro`'s code, it seems that you blind the transaction outputs before `addIssuance` and `addFee` functions. I think it causes the range proof computation error. However, as Tiero said above, we didn't write a test yet for such a case (blind a transaction with an issuance input), I'm not sure `blindOutputsWithIndex` handles correctly the issuance values... We may need extra work on the `blind` methods :thinking:

**Comment by asoltys** [comment]
Thanks for looking at this guys. @louisinger I tried moving the blinding step to just before the signing step, i.e after the fee and all inputs and outputs have been added, but still getting the same error: https://github.com/asoltys/repro/commit/36d83bf6cbc55eb83f9d016231576707b6678fd1

**Comment by louisinger** [comment]
Yeah I also test myself to blind an issuance transaction and I get the same error I think we need to update and test the blinding process

**Comment by louisinger** [comment]
@asoltys [I started to implement blinded issuance](https://github.com/vulpemventures/liquidjs-lib/pull/4#issuecomment-818826705) in PR #4. Need further work to blind the issuance outputs/inputs but you can now use `blindOutputsByIndex` to blind a transaction (with unblinded issuance outputs).

**Comment by asoltys** [comment]
Hi @louisinger thanks for working on it. I just tried again to create an unblinded issuance from a confidential tx. It seems that everything works well and I can sign the tx but my elements core regtest node rejects it when I try to broadcast it with the same error:

`sendrawtransaction RPC error: {"code":-26,"message":"bad-txns-in-ne-out, value in != value out (code 16)"}`

I pushed an update to my reproduction to simplify my test case a bit: https://github.com/asoltys/repro I wonder if I'm constructing something wrong still? If you want to try running it you may need to change the URL/port for the electrs server endpoint at the top of the file.

**Comment by louisinger** [comment]
Hey @asoltys, [last changes on Issuance PR](https://github.com/vulpemventures/liquidjs-lib/pull/4#issuecomment-902015580) should close your issue.
