### ISSUE TITLE
Use tsdx in order to improve the dev experience

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/liquidjs-lib#24]
Use [tsdx](https://github.com/formium/tsdx) to build / lint / tests (simplify the pkg.json scripts, be consistent with LDK).

**Comment by tiero** [comment]
nACK, being a fork of bitcoinjs will stick to their toolchain if possible

**Comment by louisinger** [comment]
As an alternative, we could simplify the scripts in pkg.json without adding tsdx @tiero ?
