### ISSUE TITLE
Support Liquid Testnet

### ISSUE THREAD

**Issue by tiero** [vulpemventures/liquidjs-lib#29]
This should add a new network with the right [prefixes](https://github.com/vulpemventures/go-elements/issues/177)  and change the various addresses check/encoding

**Comment by louisinger** [comment]
Do u know how to find the `bip32` [values](https://github.com/vulpemventures/liquidjs-lib/blob/211b22aee1143e363e187dea2035d30728f251e2/ts_src/networks.ts#L24-L27) ? there is also the `wif` [value](https://github.com/vulpemventures/liquidjs-lib/blob/211b22aee1143e363e187dea2035d30728f251e2/ts_src/networks.ts#L30)

**Comment by tiero** [comment]
I think those refers to https://github.com/satoshilabs/slips/blob/master/slip-0132.md if I am nost mistaken. So they could stay like regtest
