### ISSUE TITLE
issuer_pubkey is missing in IssuanceContract 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/liquidjs-lib#33]
Reference: https://github.com/vulpemventures/go-elements/pull/183/files

**Comment by tiero** [comment]
Assigned to @louisinger

**Comment by louisinger** [comment]
Looking at [Liquid dev guide](https://docs.blockstream.com/liquid/developer-guide/developer-guide-index.html#creating-raw-issuances), it also looks like that the contract hash is reversed when set in `Issuance` object
