### ISSUE TITLE
Support for additional non-standard contract fields

### ISSUE THREAD

**Issue by asoltys** [vulpemventures/liquidjs-lib#41]
It was recently brought to my attention that the issuance contract is now more strictly constructed so if you pass an object with extra fields besides the standard ones they get silently ignored:

https://github.com/vulpemventures/liquidjs-lib/commit/38ea7673ef71878ecb9822f9b0451fe08fff0a29#diff-0eae85aa617a1a8b67323fdcf42188832af778041cd1b8b7413e6a2d4fb9f6c0R43-R53

I had been adding a non-standard "file" field containing the IPFS hash of NFT files uploaded through Raretoshi, and also have been dreaming up schemes to add additional fields for grouping/categories and for identifying transfer-restricted assets and multisig signing party endpoints.

As far as I know the Blockstream asset registry allows non-standard fields as long as the keys in the contract are sorted alphabetically, so I wonder if we should revert the change that was made and just make sure the contract keys are sorted?

**Comment by tiero** [comment]
I agree! Thanks for heads up! We should def improve the API for (re)issuance. Also we want to fix the current API that wants fractional number, instead of satoshis #38
