### ISSUE TITLE
PSET with base64 that can't be decoded by elements core

### ISSUE THREAD

**Issue by asoltys** [vulpemventures/liquidjs-lib#5]
This PSET doesn't contain an issuance but it does contain a `ANYONECANPAY & SINGLE` sighash.

`cHNldP8BAHcCAAAAAAGOAZEAuavzUZPaq9dEPMzAMNHolZN3er0HZ2U/QP3F6QMAAAAA/////wEBJbJRBw4pyhkEPPM8zXMk4t2rA+zErgted8T8Dlz2yVoBAAAAAAAS1ocAF6kUGkqbsY2hKMBqGkWf1L/JaTEVmeCHAAAAAAABAUUBt6Omi68p5Vy7LZucmuRqN8Qvx++lO7OcEeXeTAKISckBAAAAAlQL5AAAF6kU3EqE/Ub+MpAddupuFeFhbUNkFryHAAABBxcWABQFbUryC46P79F533R/xs/6itaCEwEIbAJIMEUCIQDGlJdT4ddxhqe8HMjn6w+sT5Ndc104+YiQ1woRb7cmTAIgZwQwKdrjly0VjZ+G1Nvg4ZoGYgSYbMQL8uy7Xuu/TBIBIQIDnFsjIfbmGt/nyozlhtMtln3UIcuIabn1SsqAHcFy9wAA`

If I extractTransaction() I can decode the unsigned transaction hex with elements:

`0200000000018e019100b9abf35193daabd7443cccc030d1e89593777abd0767653f40fdc5e90300000000ffffffff010125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a01000000000012d6870017a9141a4a9bb18da128c06a1a459fd4bfc969311599e08700000000`

But if I try `elements-cli decodepsbt` I get:

```
error code: -22
error message:
TX decode failed Size of value was not the stated size: iostream error
```

Source code reference: https://github.com/ElementsProject/elements/blob/master/src/script/sign.h#L162

I can decode the PSET successfully with go-elements, however, so I'm not sure whether there's something wrong with our PSET serialization or if there might actually be an issue with elements core. I'm raising the issue here anyways pending further investigation.

**Comment by tiero** [comment]
Thanks @asoltys 

I suspect we could have missed the various sighash bytes in the encoding/deconding 

cc @altafan @louisinger

**Comment by altafan** [comment]
@asoltys the pset module of this library needs to be fixed because the serialization/deserialization contains some issue, besides the fact that it still misses support for important stuff like issuance or resistance.

I was able to decode the partial transaction with the [golang version](https://github.com/vulpemventures/go-elements) though. This is the correct base64 encoding for your tx:
```
cHNldP8BAHcCAAAAAAGOAZEAuavzUZPaq9dEPMzAMNHolZN3er0HZ2U/QP3F6QMAAAAA/////wEBJbJRBw4pyhkEPPM8zXMk4t2rA+zErgted8T8Dlz2yVoBAAAAAAAS1ocAF6kUGkqbsY2hKMBqGkWf1L/JaTEVmeCHAAAAAAABAUMBt6Omi68p5Vy7LZucmuRqN8Qvx++lO7OcEeXeTAKISckBAAAAAlQL5AAAF6kU3EqE/Ub+MpAddupuFeFhbUNkFryHAQcXFgAUBW1K8guOj+/Red90f8bP+orWghMBCGwCSDBFAiEAxpSXU+HXcYanvBzI5+sPrE+TXXNdOPmIkNcKEW+3JkwCIGcEMCna45ctFY2fhtTb4OGaBmIEmGzEC/Lsu17rv0wSASECA5xbIyH25hrf58qM5YbTLZZ91CHLiGm59UrKgB3BcvcAAA==
```

This way the transaction is decodable also from the elements CLI.

**Comment by tiero** [comment]
I post this here, since we are mentioning about updating the PSET (currently called Psbt) interface @altafan 

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1470
