### ISSUE TITLE
Add a method to set the locktime after creation

### ISSUE THREAD

**Issue by tiero** [vulpemventures/liquidjs-lib#63]
Now we must pass from the factory `newPset` of the creator, but there is no way to change it or add it after pset has been already created.

**Comment by tiero** [comment]
I am wrong, or we NEVER set the locktime in newPset? @altafan 

https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/psetv2/creator.ts#L104-L135

**Comment by altafan** [comment]
Updater doesn't seem to have all setters for relative input optional fields, missing:
   * `addInRipemd160Preimage` and all other preimage types
   * `addInTimeLocktime` | `addInHeightLocktime`
   *  pegin (this will be a dedicated task)

**Comment by tiero** [comment]
but locktime is a global tx field, not input specific?

**Comment by altafan** [comment]
Well, there are actually a global [`fallbackLocktime`](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/psetv2/globals.ts#L149) and per input [`requiredLocktimes`](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/psetv2/input.ts#L546-L547), and [`Pset.locktime()`](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/psetv2/pset.ts#L154) should be used to calculate the correct locktime.

The global fallback locktime can be set when creating the pset, while inputs required lockitmes should be set when updating it.

**Comment by tiero** [comment]
I have a use case where I create the Pset instance at `t0`
https://github.com/tiero/ionio-1/blob/psetv2/packages/ionio/src/Transaction.ts#L75

 and then at `t1` I want to add the lock time. Currently, I must discard the Pset and create a new one from. With old [Psbt I could set the lock time global ](https://github.com/ionio-lang/ionio/blob/master/packages/ionio/src/Transaction.ts#L95)even after the creation.
 https://github.com/tiero/ionio-1/blob/psetv2/packages/ionio/src/Transaction.ts#L100-L102

**Comment by tiero** [comment]
> I am wrong, or we NEVER set the locktime in newPset? @altafan
> 
> https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/psetv2/creator.ts#L104-L135

That being said, it seems looking at the code is not set at all when passed in `newPset` anyway

**Comment by altafan** [comment]
> That being said, it seems looking at the code is not set at all when passed in newPset anyway

This is a bug indeed :(

> I have a use case where I create the Pset instance at t0, and then at t1 I want to add the lock time. Currently, I must discard the Pset and create a new one from

You have to do this only because the updater doesn't have any method to let you update the locktime of your inputs actually.
In your case, if you don't know the locktime at t0, you should leave the global fallback locktime empty, and only at t1, when you know it,  you should use the updater to set the required locktime of one of your inputs.
