### ISSUE TITLE
[Psetv2] Allow to blind only token output in addInReissuance

### ISSUE THREAD

**Issue by altafan** [vulpemventures/liquidjs-lib#82]
The checks over the args passed to [`addInReissuance`](https://github.com/vulpemventures/liquidjs-lib/blob/7f5ef1da1c9b3cb26aad0bc28089711403254ca5/ts_src/psetv2/updater.ts#L926-L933) are too strict.
We should allow the user to eventually blind only the token output of a reissuance tx.

Given this, we can get rid of `matchAddressesType()` in favor of simply checking for the addresses' validity and ensuring that the token address is confidential (only in case of blinded resistance ofc).

**Comment by louisinger** [comment]
PR #80 closes this
