### ISSUE TITLE
pset: When I add multiple inputs with heightLockTime, it starts throwing errors

### ISSUE THREAD

**Issue by tiero** [vulpemventures/liquidjs-lib#99]
![image](https://github.com/vulpemventures/liquidjs-lib/assets/3596602/488352a0-e63f-4c1c-a9ca-e8b9358fec1a)

Doing the following woraround, fixes it
![image](https://github.com/vulpemventures/liquidjs-lib/assets/3596602/0d6d0fbc-eec3-4022-8711-75b85229fb15)

**Comment by altafan** [comment]
@tiero I didn't get the workaround from the second screenshot, which looks exactly as the first one to me.. did you upload the wrong picture by mistake?

**Comment by tiero** [comment]
yes sorry 
![image](https://github.com/vulpemventures/liquidjs-lib/assets/3596602/397cdccc-1d8e-4598-8d9e-34efdb0a93b2)

**Comment by altafan** [comment]
cc @louisinger
